### ISSUE TITLE
general_read_density_data.py

### ISSUE THREAD

**Issue by dwx741886** [sjteresi/TE_Density#153]
Thank you for developing the tool. I am currently researching the relationship between gene transcription expression and TE, and your software has been of great help to me. However, I have encountered some issues and would appreciate some guidance.

I am having trouble at this step:
![image](https://github.com/user-attachments/assets/eec1ae56-3d63-4d9f-8142-c12904216385)

Prior to this, I referred to the issues raised by others and moved the files "tmp" and "filtered_input_data" out. Within the "test333" , there are only h5 files.Midway through, I attempted to put the "filtered_input_data" back and found that the results were the same.
How can such a problem be solved? Please help me, it's important to me.

**Comment by sjteresi** [comment]
Hello,

My apologies, there is a slight mismatch between the README and the arguments to the `general_read_density_data.py` script. That last argument was not present in the Python script, please try running that command again.

 I believe this was the source of your problem. I have updated the script, please update your code with `git pull`. You should be on `v2.2.2` (commit `bcfdbbb`) now.

**Comment by dwx741886** [comment]
Thank you very much for responding to my question in such a quick time, but a new problem has arisen with the program：
(TE_density) [yuxq01@login TES_gene]$ python TE_Density/examples/general_read_density_data.py  CC_du.gene1.tsv  CC_test "CC_(.*?).h5"
2024-07-17 01:04:34 login __main__[30162] INFO import of preprocessed gene annotation... success!
2024-07-17 01:04:34 login __main__[30162] INFO
            Using the user's provided regex string 'CC_(.*?).h5' to match file
            objects and identify the proper pseudomolecule group for
            each file. Regex group 1 of this string must correspond to
            a pseudomolecule. This is needed to initialize DensityData.
            The user should verify that the pseudomolecule IDs derived from
            the GeneData correspond to the groups derived from the filename
            of the output .h5 data.

2024-07-17 01:04:34 login __main__[30162] INFO Pseudomolecule from GeneData is chr1, Regex group 1 of <re.Match object; span=(44, 62), match='CC_test/CC_chr1.h5'> is test/CC_chr1
2024-07-17 01:04:34 login __main__[30162] INFO Pseudomolecule from GeneData is chr2, Regex group 1 of <re.Match object; span=(44, 62), match='CC_test/CC_chr2.h5'> is test/CC_chr2
2024-07-17 01:04:34 login __main__[30162] INFO Pseudomolecule from GeneData is chr3, Regex group 1 of <re.Match object; span=(44, 62), match='CC_test/CC_chr3.h5'> is test/CC_chr3
2024-07-17 01:04:34 login __main__[30162] INFO Pseudomolecule from GeneData is chr4, Regex group 1 of <re.Match object; span=(44, 62), match='CC_test/CC_chr4.h5'> is test/CC_chr4
2024-07-17 01:04:34 login __main__[30162] INFO Pseudomolecule from GeneData is chr5, Regex group 1 of <re.Match object; span=(44, 62), match='CC_test/CC_chr5.h5'> is test/CC_chr5
2024-07-17 01:04:34 login __main__[30162] INFO Pseudomolecule from GeneData is chr6, Regex group 1 of <re.Match object; span=(44, 62), match='CC_test/CC_chr6.h5'> is test/CC_chr6
2024-07-17 01:04:34 login __main__[30162] INFO Pseudomolecule from GeneData is chr7, Regex group 1 of <re.Match object; span=(44, 62), match='CC_test/CC_chr7.h5'> is test/CC_chr7
2024-07-17 01:04:34 login __main__[30162] CRITICAL The strings of chromosomes in your unprocessed
                hdf5 files: ['test/CC_chr1', 'test/CC_chr2', 'test/CC_chr3', 'test/CC_chr4', 'test/CC_chr5', 'test/CC_chr6', 'test/CC_chr7', 'test/tmp/overlap/CC_chr1_overlap', 'test/tmp/overlap/CC_chr2_overlap', 'test/tmp/overlap/CC_chr3_overlap', 'test/tmp/overlap/CC_chr4_overlap', 'test/tmp/overlap/CC_chr5_overlap', 'test/tmp/overlap/CC_chr6_overlap', 'test/tmp/overlap/CC_chr7_overlap'], identified using your supplied
                regex pattern: 'CC_(.*?).h5', do not match the
                chromosomes in the GeneData: ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7'].
Traceback (most recent call last):
  File "/gss1/home/yuxq01/weixuan/heateden/TES_gene/TE_Density/examples/general_read_density_data.py", line 119, in <module>
    processed_dd_data = DensityData.from_list_gene_data_and_hdf5_dir(
  File "/gss1/home/yuxq01/weixuan/heateden/TES_gene/TE_Density/transposon/density_data.py", line 495, in from_list_gene_data_and_hdf5_dir
    raise ValueError
ValueError

I saw that there was an error similar to mine in the comments before, and you just need to put tmp to another location, but I have put this file in another location and it has not been improved, please take a look at it again, thank you.

**Comment by sjteresi** [comment]
Hello,

Can you please reformat this email and place it in the comments of the
issue? It is difficult to read in the email browser and I am hoping that
others may see the code and steps taken to fix in the issues section.
---
Scott Teresi
PhD Candidate
Edger Lab
Department of Horticulture
Michigan State University
(757) 303-1864

**Comment by dwx741886** [comment]
The question I asked before should not exist because of my negligence, because the directory name should not include "-". I have submitted it on github again：
 Thank you very much for responding to my question in such a quick time,
 but a new problem has arisen with the program：
 (TE_density) ***@***.*** TES_gene]$ python
 TE_Density/examples/general_read_density_data.py CC_du.gene1.tsv CC_test
 "CC_(.


 *?).h5" 2024-07-17 01:04:34 login main[30162] INFO import of preprocessed
 gene annotation... success! 2024-07-17 01:04:34 login main[30162] INFO
 Using the user's provided regex string 'CC_(.*?).h5' to match file
 objects and identify the proper pseudomolecule group for
 each file. Regex group 1 of this string must correspond to
 a pseudomolecule. This is needed to initialize DensityData.
 The user should verify that the pseudomolecule IDs derived from
 the GeneData correspond to the groups derived from the filename
 of the output .h5 data.

 2024-07-17 01:04:34 login *main*[30162] INFO Pseudomolecule from GeneData
 is chr1, Regex group 1 of <re.Match object; span=(44, 62),
 match='CC_test/CC_chr1.h5'> is test/CC_chr1
 2024-07-17 01:04:34 login *main*[30162] INFO Pseudomolecule from GeneData
 is chr2, Regex group 1 of <re.Match object; span=(44, 62),
 match='CC_test/CC_chr2.h5'> is test/CC_chr2
 2024-07-17 01:04:34 login *main*[30162] INFO Pseudomolecule from GeneData
 is chr3, Regex group 1 of <re.Match object; span=(44, 62),
 match='CC_test/CC_chr3.h5'> is test/CC_chr3
 2024-07-17 01:04:34 login *main*[30162] INFO Pseudomolecule from GeneData
 is chr4, Regex group 1 of <re.Match object; span=(44, 62),
 match='CC_test/CC_chr4.h5'> is test/CC_chr4
 2024-07-17 01:04:34 login *main*[30162] INFO Pseudomolecule from GeneData
 is chr5, Regex group 1 of <re.Match object; span=(44, 62),
 match='CC_test/CC_chr5.h5'> is test/CC_chr5
 2024-07-17 01:04:34 login *main*[30162] INFO Pseudomolecule from GeneData
 is chr6, Regex group 1 of <re.Match object; span=(44, 62),
 match='CC_test/CC_chr6.h5'> is test/CC_chr6
 2024-07-17 01:04:34 login *main*[30162] INFO Pseudomolecule from GeneData
 is chr7, Regex group 1 of <re.Match object; span=(44, 62),
 match='CC_test/CC_chr7.h5'> is test/CC_chr7
 2024-07-17 01:04:34 login *main*[30162] CRITICAL The strings of
 chromosomes in your unprocessed
 hdf5 files: ['test/CC_chr1', 'test/CC_chr2', 'test/CC_chr3',
 'test/CC_chr4', 'test/CC_chr5', 'test/CC_chr6', 'test/CC_chr7',
 'test/tmp/overlap/CC_chr1_overlap', 'test/tmp/overlap/CC_chr2_overlap',
 'test/tmp/overlap/CC_chr3_overlap', 'test/tmp/overlap/CC_chr4_overlap',
 'test/tmp/overlap/CC_chr5_overlap', 'test/tmp/overlap/CC_chr6_overlap',
 'test/tmp/overlap/CC_chr7_overlap'], identified using your supplied
 regex pattern: 'CC_(.*?).h5', do not match the
 chromosomes in the GeneData: ['chr1', 'chr2', 'chr3', 'chr4', 'chr5',
 'chr6', 'chr7'].
 Traceback (most recent call last):
 File
 "/gss1/home/yuxq01/weixuan/heateden/TES_gene/TE_Density/examples/general_read_density_data.py",
 line 119, in
 processed_dd_data = DensityData.from_list_gene_data_and_hdf5_dir(
 File
 "/gss1/home/yuxq01/weixuan/heateden/TES_gene/TE_Density/transposon/density_data.py",
 line 495, in from_list_gene_data_and_hdf5_dir
 raise ValueError
 ValueError

 I saw that there was an error similar to mine in the comments before, and
 you just need to put tmp to another location, but I have put this file in
 another location and it has not been improved, please take a look at it
 again, thank you.

**Comment by dwx741886** [comment]
Hello, I have a new problem, that is, the log after the code from the previous step is:
![image](https://github.com/user-attachments/assets/36797cd3-ea72-4d70-b94e-1c7ccc31905e)
Then I got a couple of HDF5 files：
![image](https://github.com/user-attachments/assets/d5e4fa75-7fca-4aa3-9b27-67ee4baa7b08)
Next, I still don't know how to read the information in the file, may I ask how to convert it into some formats of our values, such as txt or csv？

**Comment by sjteresi** [comment]
That print out statement (a print() command on a pandas dataframe) gives you a 2D version of one of the TE Density dimensions, i.e TE Density for 500 BP Upstream of all genes. You have read the information in the file. 

Since that print out is a Pandas Dataframe, you can convert that to txt, csv, or tsv using the Pandas standard library (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html)

I would suggest you modify the example script to your needs, if you are interested in multiple dimensions (TE type, window, direction) you can convert each to a 2D dataframe for ease of use, OR you can use third-party HDF5 programs such as HDFView (https://www.hdfgroup.org/downloads/hdfview/) to interact with the files more.

**Comment by dwx741886** [comment]
I tried to use pandas to read the HDF5 result file but did not succeed as shown in the figure：

![Uploading image.png…]()

May I ask how to deal with this? Please excuse my unfamiliarity with this file format

**Comment by dwx741886** [comment]
I tried to use pandas to read the HDF5 result file but did not succeed as shown in the figure：
![image](https://github.com/user-attachments/assets/a68ef84b-57b1-47b9-bc88-c46370f4b1fe)
May I ask how to deal with this? Please excuse my unfamiliarity with this file format

**Comment by dwx741886** [comment]
I'm sorry, maybe the network's down and the pictures aren't up so I'll just copy the code：

(base) [yuxq01@login XXX]$ python
Python 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:28:47) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.read_hdf('CC_chr1_SenseSwapped.HDF5')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gss1/home/yuxq01/anaconda3/lib/python3.11/site-packages/pandas/io/pytables.py", line 434, in read_hdf
    raise ValueError(
ValueError: Dataset(s) incompatible with Pandas data types, not table, or no datasets found in HDF5 file.
>>>

**Comment by sjteresi** [comment]
Please refrain from using the `read_hdf` function from the Pandas standard library. That is used for reading a Pandas object that has already been stored in HDF5 format, we did not store the data as a Pandas object within HDF5, we stored it as an array of numbers. See documentation for reasoning (https://pandas.pydata.org/docs/reference/api/pandas.read_hdf.html).

Please use the example script as you were before to take 2D subsets of the data, or use a third party tool.

**Comment by dwx741886** [comment]
Sorry, although your software is very useful, I still haven't understood how to deal with this problem. Can you provide a specific example of using pandas from SenseSwapped.HDF5 to txt or csv? thank you

**Comment by sjteresi** [comment]
The SenseSwapped file will be read from disk when you reinitialize DensityData in the Python example script.

On line 153 of the example script, please run `gene_frame_with_te_vals_of_interest.to_csv('file_out.tsv', sep='\t').

If you want a different dimension please modify the arguments to `add_te_vals_to_gene_info_pandas_from_list_hdf5()` 

If you truly want to interact with the 3D version (HDF5 format) open it in HDFView or some other third party tool

**Comment by dwx741886** [comment]
Thank you for your help all the time, I got a relatively ideal file, your software has great potential to be very useful! Good luck with your future research！
